### ISSUE TITLE
ここでタイムアウトチェックをしない方がいいと思う。

### ISSUE THREAD

**Issue by sugiyama-mitsunari** [khiemns54/rebi#6]
https://github.com/khiemns54/rebi/blob/8a881c1c8a712eab5f09c408884c61b92203384f/lib/rebi/environment.rb#L146

二重でタイムアウトを伸ばさなければいけなくなるので面倒
https://serverfault.com/questions/561901/how-to-increase-the-timeout-of-elastic-beanstalk-deployments

**Comment by khiemns54** [comment]
それはEBのタイムアウトではなく、CLIのログのポーリングのタイムアウトです。
EBのタイムアウトはまだ.ebextensionsを使います。
